### ISSUE TITLE
no attribute 'getchildren' Error while parsing drawio graph

### ISSUE THREAD

**Issue by sfc-gh-jfan** [secmerc/materialize-threats#13]
Scenario:
1. The error happened on both pip installed materialize-tool and git cloned repo tool.
2. already using the latest dfd library and the graph follows the rule(no trust boundary, no bi-directional arrow, etc)
3. Don't see any clear issue on the graph itself

Error message:

```
materialize-threats (master) $ python3 test.py --diagram /Users/jfan/Documents/test_TM1.drawio 
Traceback (most recent call last):
  File "/Users/jfan/Documents/Github/materialize-threats/test.py", line 4, in <module>
    TM.materialize()
  File "/Users/jfan/Documents/Github/materialize-threats/materialize_threats/materialize.py", line 115, in materialize
    graph = MxUtils.parse_from_xml(file=args.parse_args().diagram)
  File "/Users/jfan/Documents/Github/materialize-threats/materialize_threats/mx/utils/MxUtils.py", line 102, in parse_from_xml
    cells = diagram_root.find(MxConst.ROOT).getchildren()
AttributeError: 'xml.etree.ElementTree.Element' object has no attribute 'getchildren'
```

**Comment by Jo-Con-El** [comment]
Could you attach a graph that triggers this bug?
